// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_V3q7Pg8JcUtnZg0p39Y0z5iEP4F3ks',
    appId: '1:111748375945:web:6d731f4df4eeaebf9bed58',
    messagingSenderId: '111748375945',
    projectId: 'amyr-application',
    authDomain: 'amyr-application.firebaseapp.com',
    storageBucket: 'amyr-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDz_8s1K1QzuybfQYIu3pcwLisBHNSf4',
    appId: '1:111748375945:android:6b344520e55148a59bed58',
    messagingSenderId: '111748375945',
    projectId: 'amyr-application',
    storageBucket: 'amyr-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUbVGt4hHfFD2QvY9EK-0mRBXTstTlHI',
    appId: '1:111748375945:ios:b783bd6b1e1077919bed58',
    messagingSenderId: '111748375945',
    projectId: 'amyr-application',
    storageBucket: 'amyr-application.appspot.com',
    iosBundleId: 'com.example.amyrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFUbVGt4hHfFD2QvY9EK-0mRBXTstTlHI',
    appId: '1:111748375945:ios:b783bd6b1e1077919bed58',
    messagingSenderId: '111748375945',
    projectId: 'amyr-application',
    storageBucket: 'amyr-application.appspot.com',
    iosBundleId: 'com.example.amyrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0_V3q7Pg8JcUtnZg0p39Y0z5iEP4F3ks',
    appId: '1:111748375945:web:a54bfc658002290a9bed58',
    messagingSenderId: '111748375945',
    projectId: 'amyr-application',
    authDomain: 'amyr-application.firebaseapp.com',
    storageBucket: 'amyr-application.appspot.com',
  );

}